### ISSUE TITLE
grub efi loaders are broken.

### ISSUE THREAD

**Issue by srikalyan** [cobbler/cobbler.github.io#125]
Latest GRUB EFI loaders (tested only x86-64 bit version) seems to be broken with SuperMicro x10sdv-tln4f chip in UEFI mode which was working fine with the previous version. During the PXE, I could see that grub file is being requested but grub seems to be crashing and entering into a minimal shell. Does not work with BIOS versions

1. 1.2
2. 1.1c

The NIC being used is Intel X552/X557-AT 10G BASE

Please let me know if you need any other information.

**Comment by jmaas** [comment]
Thanks for reporting, and sorry for late response!

The loaders are currently limited to grub 1. grabbed from the latest rhel 6.x
I think they may have been updated after this report; please report issues on the cobbler/cobbler repo instead. 

Thanks
