### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by aleksashka** [cobbler/cobbler.github.io#127]
I noticed that [Kickstart Templating](http://cobbler.github.io/manuals/2.8.0/3/5_-_Kickstart_Templating.html) page in section **Snippets** references [Kickstart Snippets](http://cobbler.github.io/manuals/2.8.0/3/Kickstart-snippets) page, which does not exist. I presume that right link should be [Snippets](http://cobbler.github.io/manuals/2.8.0/3/6_-_Snippets.html) and I was going to add a fix to https://github.com/cobbler/cobbler.github.io/blob/master/manuals/2.8.0/3/5_-_Kickstart_Templating.html and change line
`<p>Read more at <a href="Kickstart-snippets">Kickstart Snippets</a></p>`
to
`<p>Read more at <a href="/manuals/2.8.0/3/6_-_Snippets.html">Snippets</a></p>`
but then I noticed that this is not the only broken link.

E.g.:
[Kickstart Templating](http://cobbler.github.io/manuals/2.8.0/3/5_-_Kickstart_Templating.html) contains 5 broken links (only absolute links are not broken).
[Snippets](http://cobbler.github.io/manuals/2.8.0/3/6_-_Snippets.html) has 2 broken links
[Cobbler Import](http://cobbler.github.io/manuals/2.8.0/3/2/4_-_Import.html) has 2 broken links

Is this a problem with some kind of a template? If not, then is it OK if I create a pull request with the changes similar to described above?

**Comment by jmaas** [comment]
I think i've fixed them.

If you want to contribute please fix the .MD files and use the generate script to create the static html files.
By editing the html files directly you loose all changes after a generate.
