### ISSUE TITLE
kickstart issue in cobbler through  spacewalk 

### ISSUE THREAD

**Issue by afifss81** [cobbler/cobbler.github.io#129]
Hi ,
I managed to configure kickstart on spacewalk and I can get the host installed by kickstart but I am facing issue in kickstart file it self .

Whenever I updated the Partitioning option under as example systems --> kickstart --> Profiles --> profile name --> system details --> partitioning , the kick start do not apply it. Below all the details needed , do i missed any thing ?

below all the details 
I am trying to apply the below partations from KS file :

part /boot/efi --fstype="efi" --ondisk=sda --size=256 --fsoptions="umask=0077,shortname=winnt"
part pv.2127 --fstype="lvmpv" --ondisk=sda --size=1 --grow
part /boot --fstype="xfs" --ondisk=sda --size=512
volgroup vg_os --pesize=102400 pv.2127
logvol /  --fstype="xfs" --size=16384  --name=root --vgname=vg_os
logvol /home  --fstype="xfs" --size=2048 --name=home --vgname=vg_os
logvol swap  --fstype="swap" --size=4096 --name=swap --vgname=vg_os
logvol /var/log/audit  --fstype="xfs" --size=4096 --name=var_log_audit --vgname=vg_os
logvol /var/log  --fstype="xfs" --size=4096 --name=var_log --vgname=vg_os
logvol /var  --fstype="xfs" --size=16384 --name=var --vgname=vg_os

whenever I do the kickstart  it use the auto partition not what I applied in the KS file. 

I make  sure that I apply the below :

1- run "cobbler sync" after I update the kickstart option
2- Organization Default Profile is selected under systems --> kickstart --> Profiles --> profile name --> Details --> Organization Default Profile
3-profile pointing to the right KS file as shown below :
cobbler profile report --name=centos7-x86_64-minimal:1:USIP
Name                           : centos7-x86_64-minimal:1:USIP
Comment                        :
DHCP Tag                       : default
Distribution                   : centos7-x86_64-server:1:USIP
Enable PXE Menu?               : True
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart                      : /var/lib/rhn/kickstarts/wizard/centos7-x86_64-minimal--1.cfg
Kickstart Metadata             : {'org': 1, 'SPACEWALK_registration_type': 'reactivation'}
Management Classes             : []
Name Servers                   : []
Name Servers Search Path       : []
Owners                         : ['admin']
Parent Profile                 :
Red Hat Management Key         : 1-d6c1023ef6b4f3481ae6ff6c77dfa010,1-ec3ad603bbc50ee535d794296b4cdc0d
Red Hat Management Server      : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : 1
Virt Bridge                    : virbr0
Virt CPUs                      : 1
Virt File Size(GB)             : 3
Virt Path                      :
Virt RAM (MB)                  : 1024
Virt Type                      : qemu

4-kickstart file /var/lib/rhn/kickstarts/wizard/centos7-x86_64-minimal--1.cfg have the new data I added from spacewalk as example the partition tuff as shown below  

part /boot/efi --fstype="efi" --ondisk=sda --size=256 --fsoptions="umask=0077,shortname=winnt"
part pv.2127 --fstype="lvmpv" --ondisk=sda --size=1 --grow
part /boot --fstype="xfs" --ondisk=sda --size=512
volgroup vg_os --pesize=102400 pv.2127
logvol /  --fstype="xfs" --size=16384  --name=root --vgname=vg_os
logvol /home  --fstype="xfs" --size=2048 --name=home --vgname=vg_os
logvol swap  --fstype="swap" --size=4096 --name=swap --vgname=vg_os
logvol /var/log/audit  --fstype="xfs" --size=4096 --name=var_log_audit --vgname=vg_os
logvol /var/log  --fstype="xfs" --size=4096 --name=var_log --vgname=vg_os
logvol /var  --fstype="xfs" --size=16384 --name=var --vgname=vg_os

5-the client is using the correct profile name . 

# cobbler system report --name=ipac01
Name                           : ipac01
Comment                        :
Gateway                        :
Hostname                       : ipac01
Image                          :
IPv6 Autoconfiguration         : False
IPv6 Default Device            :
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart                      : <<inherit>>
Kickstart Metadata             : {}
Management Classes             : []
Name Servers                   : []
Name Servers Search Path       : []
Netboot Enabled                : True
Owners                         : ['admin']
Power Management Address       :
Power ID                       :
Power Password                 :
Power Management Type          : ipmitool
Power Username                 :
Profile                        : centos7-x86_64-minimal:1:USIP
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt CPUs                      : <<inherit>>
Virt File Size(GB)             : <<inherit>>
Virt Path                      : <<inherit>>
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : <<inherit>>
Interface =====                : eth0
Bonding Opts                   :
Bridge Opts                    :
DHCP Tag                       :
DNS Name                       :
Master Interface               :
Interface Type                 :
IP Address                     : xxxxxxxxxxxxx
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 00:1a:4a:16:01:77
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :

**Comment by jmaas** [comment]
This is the issue tracker for the cobbler website.

Please use the mailing list for any further question: cobbler-users@groups.google.com
