### ISSUE TITLE
Links under MANUALS in Footer not working

### ISSUE THREAD

**Issue by gzuckerman** [cobbler/cobbler.github.io#153]
There are two links under the 'MANUALS' section in the footer that do no work, I've looked at the repo and can't see a folder for Manuals so currently the below are directing to 404s:

MANUALS > 2.6.x
MANUALS > Developer

Might be worth removing these links if there's nothing to link to at present. I'll submit a pull request for this if you agree.

**Comment by SchoolGuy** [comment]
PR already merged. So this can be closed I think.
